SELECT C1.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS C1 JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C2
                                       ON C1.CAR_ID = C2.CAR_ID AND C1.CAR_TYPE = '세단' AND MONTH(C2.START_DATE) = 10
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;