SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I JOIN ITEM_TREE AS T ON I.ITEM_ID = T.ITEM_ID
WHERE I.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM ITEM_INFO JOIN ITEM_TREE
                        WHERE ITEM_INFO.ITEM_ID = ITEM_TREE.PARENT_ITEM_ID)
ORDER BY ITEM_ID DESC;